# Generated by Django 2.2.10 on 2021-06-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Poll')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('finish_date', models.DateTimeField(blank=True, verbose_name='Finish time')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2500, verbose_name='Text')),
                ('questions_type', models.CharField(choices=[('answer with text', 'answer with text'), ('choice one answer', 'choice one answer'), ('multiple choice answer', 'multiple choice answer')], default='answer with text', max_length=30, verbose_name='Type')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api_polls.Polls', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='UsersTextAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=3500, verbose_name='Users text answer')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_answer', to='api_polls.Questions', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Users Answer',
                'verbose_name_plural': 'Users Answers',
            },
        ),
    ]
