# Generated by Django 2.2.10 on 2021-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questions_type',
            field=models.CharField(choices=[('answer with text', 'answer with text'), ('choice one answer', 'choice one answer'), ('multiple choice answer', 'multiple choice answer')], default='answer with text', max_length=35, verbose_name='Type'),
        ),
    ]
