# Generated by Django 2.2.10 on 2021-06-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_polls', '0002_auto_20210616_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstextanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api_polls.Questions', verbose_name='question'),
        ),
    ]
